[2016-12-15 12:19:10,206] WARNING % : Not Found: /
[2016-12-15 12:43:34,128] WARNING % : Not Found: /
[2016-12-15 12:45:59,469] WARNING % : Not Found: /
[2016-12-15 12:46:34,424] WARNING % : Not Found: /
[2016-12-15 12:50:31,720] WARNING % : Not Found: /
[2016-12-15 12:50:35,443] WARNING % : Not Found: /favicon.ico
[2016-12-16 13:58:16,788] WARNING % : Not Found: /
[2016-12-16 14:00:59,976] WARNING % : Not Found: /
[2016-12-16 14:01:19,707] WARNING % : Not Found: /
[2016-12-16 14:08:37,874] WARNING % : Not Found: /
[2017-03-22 13:11:10,877] WARNING % : Not Found: /
[2017-03-22 13:15:32,978] WARNING % : Not Found: /en/`/en/emplois/searchJobs/
[2017-03-22 13:15:33,336] WARNING % : Not Found: /favicon.ico
[2017-03-22 13:17:41,864] WARNING % : Not Found: /en/`/en/emplois/searchJobs/
[2017-03-22 13:17:51,346] WARNING % : Not Found: /en/`/en/emplois/searchJobs/
[2017-03-22 13:22:31,156] WARNING % : Not Found: /
[2017-03-22 13:24:06,336] WARNING % : Not Found: /
[2017-03-22 13:24:06,362] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1402, in get_library
    ','.join(tried_modules)))
django.template.base.InvalidTemplateLibrary: Template library search_form_url not found, tried django.templatetags.search_form_url,django.contrib.admin.templatetags.search_form_url,django.contrib.staticfiles.templatetags.search_form_url,django.contrib.humanize.templatetags.search_form_url,django_extensions.templatetags.search_form_url,debug_toolbar.templatetags.search_form_url,rest_framework.templatetags.search_form_url,crispy_forms.templatetags.search_form_url,bootstrap_pagination.templatetags.search_form_url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
django.template.base.TemplateSyntaxError: 'search_form_url' is not a valid tag library: Template library search_form_url not found, tried django.templatetags.search_form_url,django.contrib.admin.templatetags.search_form_url,django.contrib.staticfiles.templatetags.search_form_url,django.contrib.humanize.templatetags.search_form_url,django_extensions.templatetags.search_form_url,debug_toolbar.templatetags.search_form_url,rest_framework.templatetags.search_form_url,crispy_forms.templatetags.search_form_url,bootstrap_pagination.templatetags.search_form_url
[2017-03-22 13:24:28,361] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1402, in get_library
    ','.join(tried_modules)))
django.template.base.InvalidTemplateLibrary: Template library search_form_url not found, tried django.templatetags.search_form_url,django.contrib.admin.templatetags.search_form_url,django.contrib.staticfiles.templatetags.search_form_url,django.contrib.humanize.templatetags.search_form_url,django_extensions.templatetags.search_form_url,debug_toolbar.templatetags.search_form_url,rest_framework.templatetags.search_form_url,crispy_forms.templatetags.search_form_url,bootstrap_pagination.templatetags.search_form_url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
django.template.base.TemplateSyntaxError: 'search_form_url' is not a valid tag library: Template library search_form_url not found, tried django.templatetags.search_form_url,django.contrib.admin.templatetags.search_form_url,django.contrib.staticfiles.templatetags.search_form_url,django.contrib.humanize.templatetags.search_form_url,django_extensions.templatetags.search_form_url,debug_toolbar.templatetags.search_form_url,rest_framework.templatetags.search_form_url,crispy_forms.templatetags.search_form_url,bootstrap_pagination.templatetags.search_form_url
[2017-03-22 13:34:21,713] WARNING % : Not Found: /en/{ search_form_url}
[2017-03-22 13:34:58,945] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'search_form_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
django.template.base.TemplateSyntaxError: Invalid block tag: 'search_form_url'
[2017-03-22 13:35:10,056] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'search_form_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
django.template.base.TemplateSyntaxError: Invalid block tag: 'search_form_url'
[2017-03-22 13:37:18,319] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'some_function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
django.template.base.TemplateSyntaxError: Invalid block tag: 'some_function'
[2017-03-22 13:38:20,422] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'some_function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
django.template.base.TemplateSyntaxError: Invalid block tag: 'some_function'
[2017-03-22 13:38:52,005] WARNING % : Not Found: /
[2017-03-22 13:43:11,121] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\templatetags\search_form_url.py", line 9, in current_time
    return get_current_site+format_string+"/searchJobs/"
TypeError: unsupported operand type(s) for +: 'function' and 'str'
[2017-03-22 13:43:14,248] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\templatetags\search_form_url.py", line 9, in current_time
    return get_current_site+format_string+"/searchJobs/"
TypeError: unsupported operand type(s) for +: 'function' and 'str'
[2017-03-22 13:45:50,389] ERROR % : Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\templatetags\search_form_url.py", line 9, in current_time
    return get_current_site+format_string+"/searchJobs/"
TypeError: unsupported operand type(s) for +: 'function' and 'str'
[2017-03-22 13:49:13,346] WARNING % : Not Found: //en//searchJobs/
[2017-03-22 13:49:57,272] ERROR % : Internal Server Error: /en/searchJobs/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\views.py", line 368, in job_search
    'language_switcher_off':True})
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1394, in get_library
    lib = import_library(taglib_module)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\template\base.py", line 1333, in import_library
    mod = import_module(taglib_module)
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\templatetags\search_form_url.py", line 10
    return format_string+"searchJobs/"
                                     ^
IndentationError: unindent does not match any outer indentation level
[2017-03-22 13:51:23,778] WARNING % : Not Found: /
[2017-03-22 13:54:32,135] WARNING % : Not Found: /
[2017-03-22 13:55:15,313] WARNING % : Not Found: /
[2017-03-22 13:58:58,378] WARNING % : Not Found: /
[2017-03-22 13:59:43,376] WARNING % : Not Found: /
[2017-03-22 14:53:11,069] ERROR % : Internal Server Error: /fr/emplois/download/
Traceback (most recent call last):
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gmondesi\Documents\GitHub\cityjobs\applications\emplois\views.py", line 305, in download
    response = HttpResponse(mimetype='application/force-download')
  File "C:\Users\gmondesi\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\http\response.py", line 340, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
[2017-03-22 16:46:00,259] WARNING % : Not Found: /admin/login
[2017-03-22 16:49:24,111] WARNING % : Not Found: /en-us/emplois/
[2017-03-22 16:49:24,214] WARNING % : Not Found: /about
[2017-03-22 16:52:30,544] WARNING % : Not Found: /en-us/emplois/
[2017-03-22 16:52:30,656] WARNING % : Not Found: /about
[2017-03-22 16:58:46,940] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 16:58:47,009] WARNING % : Not Found: /emplois/
[2017-03-22 17:05:40,473] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:05:40,510] WARNING % : Not Found: /emplois/
[2017-03-22 17:07:07,749] WARNING % : Not Found: /indexapp/
[2017-03-22 17:07:18,813] WARNING % : Not Found: /indexapp/
[2017-03-22 17:07:52,076] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:07:52,095] WARNING % : Not Found: /emplois/
[2017-03-22 17:07:58,943] WARNING % : Not Found: /indexapp/
[2017-03-22 17:08:18,998] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:08:19,012] WARNING % : Not Found: /emplois/
[2017-03-22 17:08:43,235] WARNING % : Not Found: /indexapp/
[2017-03-22 17:09:04,800] WARNING % : Not Found: /indexapp
[2017-03-22 17:09:13,000] WARNING % : Not Found: /indexapp
[2017-03-22 17:10:09,946] WARNING % : Not Found: /
[2017-03-22 17:10:45,226] WARNING % : Not Found: /
[2017-03-22 17:11:08,260] WARNING % : Not Found: /emplois
[2017-03-22 17:11:22,569] WARNING % : Not Found: /
[2017-03-22 17:13:43,282] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:13:43,299] WARNING % : Not Found: /emplois/
[2017-03-22 17:14:05,525] WARNING % : Not Found: /indexapp/
[2017-03-22 17:14:05,570] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:14:05,582] WARNING % : Not Found: /emplois/
[2017-03-22 17:15:13,247] WARNING % : Not Found: /indexapp/
[2017-03-22 17:15:13,292] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:15:13,309] WARNING % : Not Found: /emplois/
[2017-03-22 17:17:51,745] WARNING % : Not Found: /indexapp/
[2017-03-22 17:17:51,794] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:17:51,808] WARNING % : Not Found: /emplois/
[2017-03-22 17:18:09,757] WARNING % : Not Found: /indexapp/
[2017-03-22 17:18:09,803] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:18:09,817] WARNING % : Not Found: /emplois/
[2017-03-22 17:18:31,422] WARNING % : Not Found: /indexapp/
[2017-03-22 17:18:31,473] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:18:31,490] WARNING % : Not Found: /emplois/
[2017-03-22 17:20:07,503] WARNING % : Not Found: /indexapp/
[2017-03-22 17:20:07,556] WARNING % : Not Found: /emplois/sdfjal
[2017-03-22 17:20:07,573] WARNING % : Not Found: /emplois/
