[2016-11-07 02:05:45,719] WARNING % : Not Found: /favicon.ico
[2016-11-07 02:05:45,921] WARNING % : Not Found: /favicon.ico
[2016-11-07 02:19:51,339] ERROR % : Internal Server Error: /
Traceback (most recent call last):
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 16, in url
    return static(path)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/home/guinslym/Documents/lineez/python3env/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/blog.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0xb4d83c8c>.
